language: julia

os:
  - linux
  - osx

julia:
  - release
  # - nightly

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi 
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Profiles"); Pkg.checkout("Plots", "dev"); Pkg.test("Profiles"; coverage=true)'
